from enum import Enum

OperatorNames = [
    'TILDE',
    'PLUS',
    'INC',
    'MINUS',
    'DEC',
    'STAR',
    'POWER',
    'DIV',
    'BAND',
    'LAND',
    'BOR',
    'LOR',
    'XOR',
    'MOD',
    'DOLLAR',
    'AT',
    'NOT',
    'GRE',
    'GREQ',
    'LE',
    'LEQ',
    'EQ',
    'QUES',
    'COLON',
    'ASSIGN',
    'DOT',
    'QUOTE',
    'DOUBLEQUOTE',
    'SHR',
    'SHL',
    'RANGE',
    'SEMICOLON',
    'OPENPAREN',
    'CLOSEPAREN',
    'OPENSQUARE',
    'CLOSESQUARE',
    'OPENCURLY',
    'CLOSECURCLY',
    'FNARR',
    'COMMA',
    'CUSTOM_OP',
    'TYPEOF',
    'LOOP',
]

Operator = Enum('Operator', " ".join(OperatorNames))

operatorMap = {
    "~": Operator.TILDE,
    "+": Operator.PLUS,
    "-": Operator.MINUS,
    "*": Operator.STAR,
    "**": Operator.POWER,
    "/": Operator.DIV,
    "&": Operator.BAND,
    "&&": Operator.LAND,
    "|": Operator.BOR,
    "||": Operator.LOR,
    "^": Operator.XOR,
    "%": Operator.MOD,
    "$": Operator.DOLLAR,
    "@": Operator.AT,
    "!": Operator.NOT,
    ">": Operator.GRE,
    ">=": Operator.GREQ,
    "<": Operator.LE,
    "<=": Operator.LEQ,
    "=": Operator.EQ,
    "?": Operator.QUES,
    ":": Operator.COLON,
    ":=": Operator.ASSIGN,
    ".": Operator.DOT,
    "\'": Operator.QUOTE,
    "\"": Operator.DOUBLEQUOTE,
    ">>": Operator.SHR,
    "<<": Operator.SHL,
    "..": Operator.RANGE,
    ";": Operator.SEMICOLON,
    "(": Operator.OPENPAREN,
    ")": Operator.CLOSEPAREN,
    "[": Operator.OPENSQUARE,
    "]": Operator.CLOSESQUARE,
    "{": Operator.OPENCURLY,
    "}": Operator.CLOSECURCLY,
    "=>": Operator.FNARR,
    ",": Operator.COMMA,
    "?*": Operator.LOOP
}
